version: '3.8'
services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 site_1:app
    volumes:
      - ./app.db:/app/app.db
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx_config:/etc/nginx/conf.d  # <-- UPDATED PATH
    depends_on:
      - web