version: "3.8"

services:
  duckly:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: duckly_container
    ports:
      - "1800:1800"
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped